#!/bin/bash
# Install Jenkins Allure Plugin and Configure

echo "=========================================="
echo "Jenkins Allure Plugin Setup Guide"
echo "=========================================="
echo ""
echo "The Allure plugin needs to be installed in Jenkins."
echo ""
echo "OPTION 1: Install via Jenkins UI (RECOMMENDED)"
echo "=============================================="
echo ""
echo "1. Open Jenkins: http://localhost:8080"
echo "2. Click: 'Manage Jenkins' (left sidebar)"
echo "3. Click: 'Plugins' (or 'Manage Plugins')"
echo "4. Click: 'Available plugins' tab"
echo "5. Search for: 'Allure'"
echo "6. Check: 'Allure' plugin"
echo "7. Click: 'Install without restart'"
echo "8. Wait for installation to complete"
echo ""
echo "Then configure Allure:"
echo "9. Go to: Manage Jenkins → Tools"
echo "10. Scroll to 'Allure Commandline'"
echo "11. Click 'Add Allure Commandline'"
echo "12. Name: 'Allure'"
echo "13. Check: 'Install automatically'"
echo "14. Choose latest version from dropdown"
echo "15. Click 'Save'"
echo ""
echo "OPTION 2: Check Current Plugin Status"
echo "======================================"
echo ""

# Check if we can access Jenkins
if curl -s http://localhost:8080/pluginManager/available > /dev/null 2>&1; then
    echo "✓ Jenkins is accessible"
    echo ""
    echo "Visit: http://localhost:8080/pluginManager/available"
    echo "Search for 'Allure' and install it"
else
    echo "Need to authenticate to check plugins"
    echo "Go to Jenkins UI to install manually"
fi

echo ""
echo "=========================================="
echo "After Installing the Plugin"
echo "=========================================="
echo ""
echo "1. Go to your job: RF-Automation-Integration"
echo "2. Click: 'Configure'"
echo "3. Scroll to 'Post-build Actions'"
echo "4. Click: 'Add post-build action'"
echo "5. Select: 'Allure Report'"
echo "6. Results path: allure-results"
echo "7. Click 'Save'"
echo ""
echo "NOW when you run builds, you'll see 'Allure Report' link!"
echo ""
echo "=========================================="
echo "Alternative: View Jenkins Workspace Results"
echo "=========================================="
echo ""
echo "Jenkins stores results in its workspace."
echo "To generate report from Jenkins results:"
echo ""
echo "1. Find Jenkins workspace (usually /var/lib/jenkins/workspace/)"
echo "2. Or download allure-results from Jenkins build artifacts"
echo "3. Generate report manually:"
echo "   allure generate /path/to/jenkins/workspace/RF-Automation-Integration/allure-results"
echo ""
