#!/bin/bash
# Manual Jenkins Job Creation Guide

echo "=========================================="
echo "Jenkins Job Manual Setup"
echo "=========================================="
echo ""
echo "Jenkins is running at: http://localhost:8080"
echo ""
echo "STEP 1: Get Initial Admin Password"
echo "-----------------------------------"
if [ -f /var/lib/jenkins/secrets/initialAdminPassword ]; then
    JENKINS_PASS=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)
    echo "Initial Admin Password: $JENKINS_PASS"
    echo ""
    echo "Save this password!"
else
    echo "Initial password not found. You may have already configured Jenkins."
    echo "Use your existing credentials."
fi

echo ""
echo "STEP 2: Complete Jenkins Setup (if first time)"
echo "----------------------------------------------"
echo "1. Open http://localhost:8080 in Chrome"
echo "2. Paste the password above"
echo "3. Click 'Install suggested plugins' (wait ~5 minutes)"
echo "4. Create admin user (or click 'Continue as admin')"
echo "5. Keep default URL and click 'Save and Finish'"
echo ""

echo "STEP 3: Create the Pipeline Job"
echo "--------------------------------"
echo "1. Click 'New Item' (top left)"
echo "2. Item name: RF-Automation-Integration"
echo "3. Select: 'Pipeline'"
echo "4. Click 'OK'"
echo ""

echo "STEP 4: Configure the Job"
echo "-------------------------"
echo "In the configuration page:"
echo ""
echo "A. Check 'This project is parameterized'"
echo "   Add these parameters (click 'Add Parameter'):"
echo ""
echo "   1. Choice Parameter:"
echo "      Name: TEST_SUITE"
echo "      Choices (one per line):"
echo "        All Tests"
echo "        PoPo Tests Only"
echo "        Functional Tests Only"
echo "        Custom (use tags)"
echo ""
echo "   2. String Parameter:"
echo "      Name: TEST_TAGS"
echo "      Default Value: (leave empty)"
echo ""
echo "   3. String Parameter:"
echo "      Name: TEST_INCLUDE"
echo "      Default Value: (leave empty)"
echo ""
echo "   4. String Parameter:"
echo "      Name: TEST_EXCLUDE"
echo "      Default Value: (leave empty)"
echo ""
echo "   5. Boolean Parameter:"
echo "      Name: ENABLE_RF_PHYSICS"
echo "      Default: checked"
echo ""
echo "   6. Choice Parameter:"
echo "      Name: NOISE_FLOOR_DBM"
echo "      Choices:"
echo "        -120"
echo "        -110"
echo "        -100"
echo "        -90"
echo ""
echo "   7. Boolean Parameter:"
echo "      Name: UPLOAD_TO_ELASTICSEARCH"
echo "      Default: checked"
echo ""
echo "   8. Boolean Parameter:"
echo "      Name: GENERATE_ALLURE_REPORT"
echo "      Default: checked"
echo ""
echo "B. Scroll down to 'Pipeline' section:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: $(pwd)"
echo "   - Branch Specifier: */integration"
echo "   - Script Path: Jenkinsfile.integration"
echo ""
echo "C. Click 'Save'"
echo ""

echo "STEP 5: Run Your First Build"
echo "----------------------------"
echo "1. Click 'Build with Parameters'"
echo "2. Select your options"
echo "3. Click 'Build'"
echo ""

echo "=========================================="
echo "QUICK ALTERNATIVE: Use Jenkins CLI"
echo "=========================================="
echo ""
echo "Run this to auto-create the job:"
echo ""
echo "  sudo bash scripts/configure_jenkins.sh"
echo ""
echo "Note: This requires Jenkins to be fully configured first"
echo ""
